language: node_js
node_js:
  - "0.12"
jdk:
  - oraclejdk8
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt font
script: grunt
cache:
  directories:
    - node_modules