language: node_js
node_js:
  - "0.12"
before_install:
  - npm install -g grunt-cli
  - java install oraclejdk8
install: npm install
before_script: grunt font
script: grunt
cache:
  directories:
    - node_modules